runtime: python310  # Specify the correct Python version (python310 is closest to 3.13)

entrypoint: gunicorn -b :$PORT app:app  # Use Gunicorn to run the app

instance_class: F2  # Optional: Defines the machine type (F2 is a balanced machine for small workloads)

handlers:
  - url: /static
    static_dir: static  # Ensure to include any static files (CSS, JS, images)

  - url: /.*  # Route all requests to your Flask app
    script: auto