runtime: python310  # Use the correct Python runtime version

entrypoint: gunicorn -b :$PORT app:app  # Entry point for the app

instance_class: F2  # Machine type

env_variables:
  GOOGLE_MAPS_API_KEY: "AIzaSyBVu-O6H8tM6EZE6_g-uAdj63XwEHa8CVY"  # Add your actual Google Maps API key here

handlers:
  - url: /static
    static_dir: static  # Serve static files

  - url: /.*
    script: auto
